### ISSUE TITLE
Usage Abstraction

### ISSUE THREAD

**Issue by blainsmith** [oddnetworks/oddcast#1]
I was curious if there was any advantages to treating everything like a giant network instead of initializing channel types. Code is better than words so:

```js
var oddcast = require('oddcast')();

oddcast.use({role: 'catalog'}, TRANSPORT, options);
oddcast.use({role: 'views'}, TRANSPORT, options);
oddcast.use({role: 'sync'}, TRANSPORT, options);

oddcast.broadcast();
oddcast.observe();

oddcast.send(); // Send a commend without a response
oddcast.receive(); // Receive the command formerly .addHandler

oddcast.request(); // Send a request, expecting a response
oddcast.response(); // Respond to a requst formerly .registerHandler

oddcast.remove(); // Since its all pattern matching a single .remove can replace the removing of handlers
```

More to chat if you want, but trying to think of it from an implementation side...out loud.

**Comment by kixxauth** [comment]
Initially I thought having a single oddcast instance support all the broadcast, observe, send, receive, request, and response methods was a great idea, but couple days I've been thinking that we lose that explicitness of what a particular channel is capable of.

For example, implementing a transport which transparently handles remote requests in the request/response model requires an endpoint discovery system built into the transport. Good service discovery is really complicated in distributed systems, so many transports may just leave this out in favor of only using broadcast and command channels. So what happens if the request/response channel is not supported by the transport? We would have to throw an error if request() or response() are called, or return a rejected promise.

I think it is better to explicitly say what kind of channel is being created and the capabilities of the underlying transport by explicitly creating channels with named functions.

However, I agree the method names could be more succinct, and a single remove method will work for everything, cuz pattern matching.

```JS
var oddcast = require('oddcast')();
var commands = oddcast.commandChannel();
var events = oddcast.eventsChannel();
var req = oddcast.requestChannel();

events.use({role: 'catalog'}, TRANSPORT, options);
request.use({role: 'views'}, TRANSPORT, options);
commands.use({role: 'sync'}, TRANSPORT, options);

events.broadcast();
events.observe();

commands.send(); // Send a commend without a response
commands.receive(); // Receive the command formerly .addHandler

req.request(); // Send a request, expecting a response
req.respond(); // Respond to a requst formerly .registerHandler

oddcast.remove(); // Since its all pattern matching a single .remove can replace the removing of handlers
```

**Comment by blainsmith** [comment]
Nice. I was messing around last night to try and get working system up with RabbitMQ and the only thing I haven't gotten to work was the `.sub()` command to listen to events not directed at a particular service. I wonder if it is because the transport being used and its popped off the queue before it can be seen.

https://github.com/blainsmith/seneca-playground
